general.import = ["~/.config/alacritty/themes/dracula.toml"]

# "~/.config/alacritty/key-bindings.toml", 
# "~/.config/alacritty/themes/rose-pine.toml"
[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"


[terminal]
shell = "/opt/homebrew/bin/fish"
