import = ["/Users/leo/.config/alacritty/key-bindings.toml"]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

